export type InventoryStatus = 'available' | 'reserved' | 'sold'

export type Artwork = {
  id: string
  sequence: string
  title: string
  titleZh?: string
  artist: string
  year: string
  origin?: string
  medium: string
  technique?: string
  dimensions: string
  price: string
  availability: InventoryStatus
  ratio: string
  image?: string
  region?: string
}

export type ArtworkRecord = {
  id: string
  inventory_number: string
  title: string
  title_zh: string | null
  origin: string | null
  material: string
  technique: string | null
  dimensions: string
  price: string
  inventory_status: InventoryStatus
  image_url: string | null
  sort_order: number
  region?: string
}

export function mapArtworkRecord(record: ArtworkRecord): Artwork {
  return {
    id: record.inventory_number,
    sequence: String(record.sort_order).padStart(2, '0'),
    title: record.title,
    titleZh: record.title_zh ?? undefined,
    artist: record.origin ?? '',
    year: '—',
    origin: record.origin ?? undefined,
    medium: record.material,
    technique: record.technique ?? undefined,
    dimensions: record.dimensions,
    price: record.price,
    availability: record.inventory_status,
    ratio: '3 / 4',
    image: record.image_url ?? undefined,
    region: record.region,
  }
}

export const gallery = {
  name: 'OPENLAND',
  email: 'hello@yourgallery.com',
  wechat: 'your_wechat_id',
  xiaohongshu: 'OPENLAND 博物馆',
  address: ['华侨城创意文化园南区 OCAT A馆', '人类学博物馆'],
}

export const seedArtworks: Artwork[] = [
  {
    id: '2026050303',
    sequence: '01',
    title: 'Sandstone Figures',
    titleZh: '双人雕像',
    artist: '马来西亚',
    year: '~150 years ago',
    origin: '马来西亚',
    medium: 'Sandstone 砂岩',
    technique: '马来西亚传统中，通常摆放在卧室里，以象征夫妻和睦、恩爱美满。',
    dimensions: '44.5×24×27 cm / 50×27×27 cm',
    price: '￥20,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050304',
    sequence: '02',
    title: 'Hand-Carved Wooden Duck Sculptures',
    titleZh: '手工雕刻木鸭雕像',
    artist: '印度尼西亚',
    year: '—',
    origin: '印度尼西亚',
    medium: 'Wood，paint 木，颜料',
    technique: '袁老师在印度尼西亚从当地居住的欧洲艺术家手中购得（现代工艺品）',
    dimensions: '60.6×21×31 cm / 61×21 30cm',
    price: '￥4,500',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050401',
    sequence: '03',
    title: 'Buddha Head',
    titleZh: '佛头',
    artist: '印度尼西亚',
    year: '—',
    origin: '印度尼西亚',
    medium: 'Wood 木',
    technique: '背后可挂墙，需要很厚实的墙体承载，有近70-80斤',
    dimensions: '110×75×30cm',
    price: '￥20,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050301',
    sequence: '04',
    title: 'Puppet (Yoke Thay)',
    titleZh: '提线木偶',
    artist: '缅甸',
    year: '—',
    origin: '缅甸',
    medium: 'Wood, gold thread, fabric, embroidery 木，金丝，布料，刺绣',
    dimensions: '72×46×19 cm',
    price: '￥15,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050302',
    sequence: '05',
    title: 'Perahera Bronze Elephant',
    titleZh: '骑象巡游摆件',
    artist: '斯里兰卡',
    year: '—',
    origin: '斯里兰卡',
    medium: 'Copper Alloy 铜合金',
    technique: '手工使用多种工艺制作',
    dimensions: '45×45×20.5 cm',
    price: '￥45,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050311',
    sequence: '06',
    title: 'Guardian Figure',
    titleZh: '守护神',
    artist: '印度尼西亚',
    year: '~200 years ago',
    origin: '印度尼西亚',
    medium: 'Wood 木',
    technique: undefined,
    dimensions: '116/12/10cm 110/12/10cm 110/12/10cm',
    price: '￥3,500',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050305',
    sequence: '07',
    title: 'Enthroned Buddha',
    titleZh: '佛坐像',
    artist: '缅甸',
    year: '~500 years',
    origin: '缅甸',
    medium: 'Wood 木',
    technique: '缅甸的佛塔部分，家族传承/地震后获得',
    dimensions: '—',
    price: '￥500,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050308',
    sequence: '08',
    title: 'Art Installation',
    titleZh: '艺术装置',
    artist: '印度尼西亚',
    year: '—',
    origin: '印度尼西亚',
    medium: 'Iron 铁',
    technique: '袁老师在印度尼西亚从当地居住的欧洲艺术家手中购得（现代工艺品）',
    dimensions: '—',
    price: '￥180,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050309',
    sequence: '09',
    title: 'Modern Wood Artworks',
    titleZh: '现代木雕艺术品',
    artist: '印度尼西亚',
    year: '—',
    origin: '印度尼西亚',
    medium: 'Wood 木',
    technique: '袁老师在印度尼西亚从当地居住的欧洲艺术家手中购得，斑马纹但是长颈鹿的脖子，这是非写实创作，是印尼非常受欢迎的出口工艺品。',
    dimensions: '—',
    price: '￥2,500',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050413',
    sequence: '10',
    title: 'Animal Sculpture',
    titleZh: '动物塑像',
    artist: '斯里兰卡',
    year: 'Modern',
    origin: '斯里兰卡',
    medium: 'Brass 黄铜',
    technique: '纯手工制作，采取古老的失蜡法（Lost-wax casting)。工艺起源于古印度，疑似猫造型，融合了动物和图腾的审美。',
    dimensions: '—',
    price: '￥10,000',
    availability: 'sold',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050501',
    sequence: '11',
    title: 'Ancestral Figure',
    titleZh: '祖先像/守护神',
    artist: '印度尼西亚-苏门答腊',
    year: '—',
    origin: '印度尼西亚-苏门答腊',
    medium: 'Wood 木',
    technique: '双手交叠胸前或腹部，呈V型，在东南亚象征虔诚，守护或仪式感。耳垂大是长寿，地位高的象征。眼睛形状是非写实的。',
    dimensions: '—',
    price: '￥2,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050603',
    sequence: '12',
    title: 'Apsara / Devata Statue',
    titleZh: '德瓦塔雕像',
    artist: '柬埔寨',
    year: 'Angkor Period',
    origin: '柬埔寨',
    medium: 'Sandstone 砂岩',
    technique: '印度教和佛教神话中，为仙女或守护女神。 手持莲花苞，站立姿态，更符合德瓦塔的神殿守护者身份。 可能为神庙或石壁建筑的一部分。',
    dimensions: '—',
    price: '￥500,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050606',
    sequence: '13',
    title: 'Guardian Lions',
    titleZh: '守护狮（一对）',
    artist: '马来西亚',
    year: '~100 years ago',
    origin: '马来西亚',
    medium: 'Wood 木',
    technique: '很少见，相比其他砂岩雕像',
    dimensions: '—',
    price: '￥50,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050607',
    sequence: '14',
    title: 'Statue of Ganesha',
    titleZh: '象神雕像（印度教神祇）',
    artist: '印度尼西亚',
    year: '~100 years ago',
    origin: '印度尼西亚',
    medium: 'Volcanic Rock 火山岩',
    technique: '象头人身：象征大智慧。站姿相比于常见的坐姿，在东南亚石雕艺术中具有很高的艺术地位。在东南亚文化中，他不仅是智慧之神和破除障碍之神，还被视为商贸、艺术和成功的守护者。',
    dimensions: '—',
    price: '￥25,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050609',
    sequence: '15',
    title: 'Kinnara Statue',
    titleZh: '紧那罗塑像',
    artist: '泰国',
    year: '—',
    origin: '泰国',
    medium: 'Wood 木',
    technique: '东南亚神话生物，在佛教和印度教神话中，被认为是天界的乐师和歌手，象征着美妙的音乐、诗歌和永恒的爱情。',
    dimensions: '—',
    price: '￥3,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050610',
    sequence: '16',
    title: 'Gandhara Enthroned Buddha',
    titleZh: '佛坐像',
    artist: '柬埔寨',
    year: '~200 years',
    origin: '柬埔寨',
    medium: 'Schist 片岩',
    technique: '犍陀罗（Gandhara）艺术风格，最显著的特征是希腊化佛教艺术的融合，带有古希腊、罗马雕塑的神韵。头顶有肉髻，发丝呈现出波浪状的卷发。',
    dimensions: '—',
    price: '￥50,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050611',
    sequence: '17',
    title: 'Torso of Vishnu',
    titleZh: '毗湿奴躯干像',
    artist: '柬埔寨',
    year: '—',
    origin: '柬埔寨',
    medium: 'Sandstone 砂岩',
    technique: '这类造像通常是大型组雕（如佛寺、神庙中的守护者、僧侣或神祇）的一部分。',
    dimensions: '—',
    price: '￥150,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050805',
    sequence: '18',
    title: 'Buddha Head',
    titleZh: '佛头',
    artist: '马来西亚',
    year: '~300 years ago',
    origin: '马来西亚',
    medium: '花岗岩',
    technique: '东南亚早期佛教艺术和印度艺术的影子，古代东南亚工匠雕刻佛像时往往融入当地人的面部特征。保留了印度原始佛教的庄严，有犍陀罗艺术的立体感。',
    dimensions: '—',
    price: '￥70,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050901',
    sequence: '19',
    title: 'Vassel Celadon Vase',
    titleZh: '瓷花瓶（一大一小）',
    artist: '日本',
    year: 'Modern',
    origin: '日本',
    medium: 'Goryeo celadon 高丽瓷',
    technique: '日本当代因为战争和贸易原因，从韩国带了许多工匠和技术回日本，因此馆内这种器皿都是日本制造，韩国工艺。',
    dimensions: '—',
    price: '￥1,900',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050916',
    sequence: '20',
    title: 'Enthroned Buddha',
    titleZh: '佛坐像',
    artist: '马来西亚',
    year: '~100 years ago',
    origin: '马来西亚',
    medium: 'Sandstone 砂岩',
    technique: '看起来腐蚀痕迹明显的都是长期放在户外的。',
    dimensions: '—',
    price: '￥20,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026052706',
    sequence: '21',
    title: 'Buddha Head',
    titleZh: '佛头',
    artist: '柬埔寨',
    year: '~200 years',
    origin: '柬埔寨',
    medium: 'Sandstone 砂岩',
    technique: '当地村落人家里收的（不能确定）',
    dimensions: '—',
    price: '￥30,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026052709',
    sequence: '22',
    title: 'Buddhapada',
    titleZh: '佛足',
    artist: '柬埔寨',
    year: '~200 years',
    origin: '柬埔寨',
    medium: 'Sandstone 砂岩',
    technique: '不同地区的砂岩材质不同，杂质不同，也有可能放在泥土里久了侵蚀了。',
    dimensions: '—',
    price: '￥20,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026052710',
    sequence: '23',
    title: 'Buddha Head',
    titleZh: '佛头',
    artist: '缅甸',
    year: '~200 years',
    origin: '缅甸',
    medium: '夹苎工艺（麻和大漆）',
    technique: '可以保存很久很久，很轻',
    dimensions: '—',
    price: '￥15,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026052717',
    sequence: '24',
    title: 'Ancestral Figure',
    titleZh: '祖先像',
    artist: '非洲-马里',
    year: '~200 years',
    origin: '非洲-马里',
    medium: 'Wood 木',
    technique: '放在室内供奉，很少见，大都会博物馆有同类藏品。',
    dimensions: '—',
    price: '￥55,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050307',
    sequence: '25',
    title: 'Buddha Head',
    titleZh: '佛头',
    artist: '印度尼西亚',
    year: 'Modern',
    origin: '印度尼西亚',
    medium: '雨豆木',
    dimensions: '—',
    price: '￥10,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050412',
    sequence: '26',
    title: 'Buddha Head',
    titleZh: '佛头',
    artist: '马来西亚',
    year: 'Modern',
    origin: '马来西亚',
    medium: 'Bronze 青铜',
    dimensions: '—',
    price: '￥300,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050414',
    sequence: '27',
    title: 'Sandstone Statue',
    titleZh: '砂岩双人雕像',
    artist: '印度尼西亚-爪哇',
    year: '~150 years ago',
    origin: '印度尼西亚-爪哇',
    medium: 'Sandstone 砂岩',
    technique: '传统中，通常摆放在卧室里，以象征夫妻和睦、恩爱美满。',
    dimensions: '—',
    price: '待询价',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050415',
    sequence: '28',
    title: 'Ganesha Statue',
    titleZh: '象神雕像',
    artist: '柬埔寨',
    year: '~700 years ago',
    origin: '柬埔寨',
    medium: 'Volcanic Rock 火山岩',
    dimensions: '—',
    price: '￥130,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050502',
    sequence: '29',
    title: 'Ancestral Figure',
    titleZh: '祖先像/守护神',
    artist: '印度尼西亚',
    year: '~200 years',
    origin: '印度尼西亚',
    medium: 'Wood 木',
    dimensions: '—',
    price: '￥50,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050506',
    sequence: '30',
    title: 'Hornbill Bird Installation',
    titleZh: '犀鸟飞鸟装置（一对）',
    artist: '马来西亚',
    year: 'Modern',
    origin: '马来西亚',
    medium: 'Wood 木',
    dimensions: '—',
    price: '￥30,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050507',
    sequence: '31',
    title: 'Tiger Head Painted Chair',
    titleZh: '虎头彩绘椅（一对）',
    artist: '印度',
    year: '~70 years',
    origin: '印度',
    medium: '彩绘，木',
    dimensions: '—',
    price: '￥15,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050601',
    sequence: '32',
    title: 'Bronze Bell',
    titleZh: '青铜钟',
    artist: '缅甸',
    year: '~200 years',
    origin: '缅甸',
    medium: 'Bronze 青铜',
    technique: '寺庙门口的钟',
    dimensions: '—',
    price: '￥100,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050602',
    sequence: '33',
    title: 'Vishnu Statue',
    titleZh: '毗湿奴雕像',
    artist: '柬埔寨',
    year: 'Angkor Period',
    origin: '柬埔寨',
    medium: 'Sandstone 砂岩',
    technique: '柬埔寨吴哥时期风格。毗湿奴的特征是四只手臂，虽然下方两手残缺，但上方分别持有其典型法器，右（海螺），左（神轮）。',
    dimensions: '—',
    price: '待询价',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050604',
    sequence: '34',
    title: 'Enthroned Buddha',
    titleZh: '佛坐像',
    artist: '马来西亚',
    year: '~100 years ago',
    origin: '马来西亚',
    medium: 'Sandstone 砂岩',
    dimensions: '—',
    price: '￥50,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
  {
    id: '2026050612',
    sequence: '35',
    title: 'Torso of Vishnu',
    titleZh: '毗湿奴躯干像',
    artist: '柬埔寨',
    year: '—',
    origin: '柬埔寨',
    medium: 'Sandstone 砂岩',
    dimensions: '—',
    price: '￥150,000',
    availability: 'available',
    ratio: '3 / 4',
    image: undefined,
  },
]
